import 'dbhelper.dart';

class Passport {
  int? pass_id;
  bool? russia;
  bool? germany;
  bool? united_kingdom;
  bool? france;
  bool? italy;
  bool? spain;
  bool? ukraine;
  bool? poland;
  bool? romania;
  bool? netherlands;
  bool? belgium;
  bool? czech_republic;
  bool? greece;
  bool? portugal;
  bool? sweden;
  bool? hungary;
  bool? belarus;
  bool? austria;
  bool? serbia;
  bool? switzerland;
  bool? bulgaria;
  bool? denmark;
  bool? finland;
  bool? slovakia;
  bool? norway;
  bool? ireland;
  bool? croatia;
  bool? moldova;
  bool? bosnia_and_herzegovina;
  bool? albania;
  bool? lithuania;
  bool? north_macedonia;
  bool? slovenia;
  bool? latvia;
  bool? estonia;
  bool? montenegro;
  bool? luxembourg;
  bool? malta;
  bool? iceland;
  bool? andorra;
  bool? monaco;
  bool? liechtenstein;
  bool? san_marino;
  bool? vatican_city;

  Passport(this.pass_id, this.russia, this.germany, this.united_kingdom, this.france, this.italy, this.spain, this.ukraine, this.poland, this.romania, this.netherlands, this.belgium, this.czech_republic, this.greece, this.portugal, this.sweden, this.hungary, this.belarus, this.austria, this.serbia, this.switzerland, this.bulgaria, this.denmark, this.finland, this.slovakia, this.norway, this.ireland, this.croatia, this.moldova, this.bosnia_and_herzegovina, this.albania, this.lithuania, this.north_macedonia, this.slovenia, this.latvia, this.estonia, this.montenegro, this.luxembourg, this.malta, this.iceland, this.andorra, this.monaco, this.liechtenstein, this.san_marino, this.vatican_city);

  Passport.fromMap(Map<String, dynamic> map) {
    pass_id = map['id'];
    russia = map['russia'];
    germany = map['germany'];
    united_kingdom = map['united_kingdom'];
    france = map['france'];
    italy = map['italy'];
    spain = map['spain'];
    ukraine = map['ukraine'];
    poland = map['poland'];
    romania = map['romania'];
    netherlands = map['netherlands'];
    belgium = map['belgium'];
    czech_republic = map['czech_republic'];
    greece = map['greece'];
    portugal = map['portugal'];
    sweden = map['sweden'];
    hungary = map['hungary'];
    belarus = map['belarus'];
    austria = map['austria'];
    serbia = map['serbia'];
    switzerland = map['switzerland'];
    bulgaria = map['bulgaria'];
    denmark = map['denmark'];
    finland = map['finland'];
    slovakia = map['slovakia'];
    norway = map['norway'];
    ireland = map['ireland'];
    croatia = map['croatia'];
    moldova = map['moldova'];
    bosnia_and_herzegovina = map['bosnia_and_herzegovina'];
    albania = map['albania'];
    lithuania = map['lithuania'];
    north_macedonia = map['north_macedonia'];
    slovenia = map['slovenia'];
    latvia = map['latvia'];
    estonia = map['estonia'];
    montenegro = map['montenegro'];
    luxembourg = map['luxembourg'];
    malta = map['malta'];
    iceland = map['iceland'];
    andorra = map['andorra'];
    monaco = map['monaco'];
    liechtenstein = map['liechtenstein'];
    san_marino = map['san_marino'];
    vatican_city = map['vatican_city'];
  }
}